// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PerfomanceProject_API
{
    public partial class ProductivityModel
    {
        /// <summary>
        /// model input class for ProductivityModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"TaskDifficulty")]
            public float TaskDifficulty { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"TaskRating")]
            public float TaskRating { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"PlannedTime")]
            public float PlannedTime { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"RealTime")]
            public float RealTime { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Engagement")]
            public float Engagement { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"TasksPerPeriod")]
            public float TasksPerPeriod { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Label")]
            public float Label { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ProductivityModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"TaskDifficulty")]
            public float TaskDifficulty { get; set; }

            [ColumnName(@"TaskRating")]
            public float TaskRating { get; set; }

            [ColumnName(@"PlannedTime")]
            public float PlannedTime { get; set; }

            [ColumnName(@"RealTime")]
            public float RealTime { get; set; }

            [ColumnName(@"Engagement")]
            public float Engagement { get; set; }

            [ColumnName(@"TasksPerPeriod")]
            public float TasksPerPeriod { get; set; }

            [ColumnName(@"Label")]
            public float Label { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ProductivityModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
